# https://www.perplexity.ai/search/045ecda7-23bf-4d76-9155-fcb886e2425e

In [ ]:
import numpy as np
np.random.random()
np.random.random(3) #引述值的呼叫
np.random.random(size=3) #引數名稱呼叫→不用按照說明書排序
np.random.random((3,4)) #陣列 3*4的矩陣呼叫
np.random.random(size=(3,4)) #引數名稱呼叫陣列


array([[0.91668911, 0.24083643, 0.42617277, 0.75849838],
       [0.71157064, 0.78155526, 0.72123963, 0.16399982],
       [0.6863046 , 0.52438545, 0.73072352, 0.49783374]])

In [ ]:
from numpy.random import normal
normal_value = normal(size=(3,4)) #normal_value作為變數 接收傳出的值
#ndarry常用的實體屬性
type(normal_value) #查詢normal_value傳出的型態
normal_value.ndim #ndim
normal_value.size #size 12(有12筆資料)
normal_value.shape #(3,4) 3*4 的2維陣列
normal_value.dtype #float64 →浮點數

dtype('float64')

In [ ]:
#ndarray, 陣列運算
normal_value *10 #ndarry可以做數學運算，直接運算陣列中的數值

array([[-15.17969202,  -0.98591325,  11.37112754,  14.16480819],
       [-10.13787901,   9.61190639,   0.49416144,   4.10158285],
       [-13.47247021,   6.94704206,  -4.85213561,   0.46415463]])

In [20]:
#ndarray, 的統計
normal_value.sum() #全部加總
normal_value.sum(axis=0) #直行加總
normal_value.sum(axis=1) #橫列加總



array([ 0.93703305,  0.40697717, -1.09134091])